ndef: Fix text payloads getting truncated.
linux-nfc/neard pull request #26
Opened 2024-06-24 16:56 UTC by Apokalypzx

Text payloads larger than ~200 characters in length get truncated due 
to the variable 'len' being uint8_t. Changing it to uint32_t fixes 
this issue, allowing the whole text payload to be extracted.

2024-06-24 16:58 UTC, Apokalypzx commented
Fixed commit description to <72 char lines.

2024-06-26 04:33 UTC, Apokalypzx commented
New commit should compile without emitting a format warning.

2024-06-26 06:05 UTC, krzk commented
The previous commit was not merged, so please correct it instead of creating one more. IOW, squash it to previous commit.

2024-06-27 06:43 UTC, krzk requested changes
Squash the commits. This should be only one, proper commit. Not one bad and one good.

2024-06-28 22:12 UTC, Apokalypzx commented
10th time's the charm. Hopefully this PR is acceptable. I apologize for my previous mistakes, I have very little experience in contributing to upstream projects. Thank you guys for all you do.

2024-07-01 05:55 UTC, krzk requested changes
Where is the commit msg? The commits should have been fixed-up into one, which will keep the original commit message.

2024-07-02 04:58 UTC, Apokalypzx commented
I just now added the message. I figured the title was descript enough, no detailed message needed; I'm guessing no detailed message breaks protocol?

2024-07-02 10:35 UTC, merged